Models/Customer.cs
namespace WebPaymentFineros.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Customer")]
    public partial class Customer
    {
        public int CustomerId { get; set; }

        [StringLength(50)]
        public string Pw { get; set; }

        [StringLength(100)]
        public string Email { get; set; }

        [StringLength(12)]
        public string Phone { get; set; }

        [Required]
        [StringLength(255)]
        public string LastName { get; set; }

        [StringLength(255)]
        public string FirstName { get; set; }

        public int? Age { get; set; }

    }
}

Models/Payment.cs
namespace WebPaymentFineros.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Payment")]
    public partial class Payment
    {
        public int PaymentId { get; set; }

        public int CustomerId { get; set; }

        [StringLength(16)]
        public string CCNumber { get; set; }

        [StringLength(10)]
        public string CCDate { get; set; }

        [StringLength(3)]
        public string CVV { get; set; }
        [StringLength(150)]
        public string CCNameSurname { get; set; }

        public double Price { get; set; }
        public DateTime PaymentDate { get; set; }
    }
}

Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using WebPaymentFineros.Models;

namespace WebPaymentFineros.Controllers
{
    public class CustomerController : ApiController
    {
        // GET api/values
        /// <summary>
        /// Get All Customers
        /// </summary>
        /// <returns></returns>
        public IEnumerable<Customer> Get()
        {
            using (ManagerDB db = new ManagerDB())
            {
                return db.Customer.OrderByDescending(x=> x.CustomerId).ToList();
            }
        }
        // GET api/values
        /// <summary>
        /// Get Customer By Id
        /// </summary>
        /// <returns></returns>
        public Customer Get(int id)
        {
            using (ManagerDB db = new ManagerDB())
            {
                return db.Customer.Where(x => x.CustomerId == id).FirstOrDefault();
            }
        }
        // POST api/values
        /// <summary>
        /// Create New Customer 
        /// </summary>
        /// <returns></returns>
        [HttpPost]

        public string Create(Customer customer)
        {
            if (customer == null)
            {
                return "Please read Example Value";
            }
            using (ManagerDB db = new ManagerDB())
            {
                try
                {
                    if (db.Customer.Where(x => x.Email == customer.Email).ToList().Count > 0)
                    {
                        return "This Email is already exist";
                    }
                    db.Customer.Add(customer);
                    db.SaveChanges();
                    return "success";

                }
                catch (Exception ex)
                {
                    return ex.ToString();
                    throw;
                }
            }
        }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebPaymentFineros.Models;
namespace WebPaymentFineros.Controllers
{
    public class HomeController : Controller
    {
        ManagerDB db = new ManagerDB();
        // GET: Home
        public ActionResult Index()
        {
            return View(db.MyProduct);
        }
        public ActionResult Payment()
        {
            return View(db.Payment.OrderByDescending(x=> x.PaymentDate));
        }
        public ActionResult Customer()
        {
            return View(db.Customer.OrderByDescending(x=> x.CustomerId));
        }
        public ActionResult Register()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View();
            }
            return RedirectToAction("Index", "Home");
        }
        public ActionResult Login()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View();
            }
            return RedirectToAction("Index", "Home");

        }
        public ActionResult SignOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
        public ActionResult PaymentCheckOut(int id)
        {
            if (User.Identity.IsAuthenticated)
            {
                return View();
            }
            return RedirectToAction("Login", "Home");
        }
    }
}

Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebPaymentFineros.Models;
namespace WebPaymentFineros.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [AllowAnonymous]
        public string CheckUser(FormCollection formCollection)
        {
            try
            {
                //TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    ManagerDB db = new ManagerDB();
                    List<Customer> customer = new List<Customer>();
                    customer = db.GetCustomer();
                    Customer customer1 = new Customer();
                
                    string userEmail = formCollection["txtEmail"];
                    string userPass = formCollection["txtPassword"];
                 

                    if (customer.Where(x=> x.Email==userEmail && x.Pw==userPass).ToList().Count == 1)
                    {
                        customer1 = customer.Where(x => x.Email == userEmail && x.Pw == userPass).FirstOrDefault();
                        string userDetail=customer1.FirstName + ";" + customer1.CustomerId;
                        FormsAuthentication.SetAuthCookie(userDetail, false);
                       //RedirectToAction("Index", "Home");
                        return "success";
                    }
                    else
                    {
                        return "Email or Password is incorrect";
                    }
                   
                    //var url = Url.RouteUrl("custom", new { controller = "Home", action = "Mesajlar" });
                    //return RedirectToAction("Index", "Home");

                }
                return "failed";


            }
            catch
            {
                return "failed";
            }

        }
    }

}

Controllers/PaymentCheckOutController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPaymentFineros.Models;
namespace WebPaymentFineros.Controllers
{
    public class PaymentCheckOutController : Controller
    {
        // GET: PaymentCheckOut
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public string Create(FormCollection formCollection)
        {
            string result = "";
            try
            {
                //TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    if (!User.Identity.IsAuthenticated)
                    {
                        return "login";
                    }
                    ManagerDB db = new ManagerDB();
                    Payment payment = new Payment();
                    payment.CVV = formCollection["txtCVV"];
                    payment.CCNumber = formCollection["txtCCNumber"];
                    payment.CCDate = formCollection["selM"] + "/" + formCollection["selY"];
                    payment.CCNameSurname = formCollection["txtCCNameSurname"];
                    int proId = Convert.ToInt32(formCollection["hidProductId"]);
                    MyProduct pro = db.MyProduct.Where(x => x.ProductId == proId).FirstOrDefault();
                    payment.Price = pro.Price;
                    payment.PaymentDate = DateTime.Now;
                    //payment.Price = 200;
                    payment.CustomerId =Convert.ToInt32(User.Identity.Name.ToString().Split(';')[1].ToString());
                    string strParams = JsonConvert.SerializeObject(payment);
                    string urlCreate =General.GetDomain() + "api/Payment";
                    string responseFromServer = General.SendJSonData(urlCreate, strParams).Replace("\"", "");
                    if (responseFromServer == "success")
                    {
                        //RedirectToAction("Login", "Home");
                        return responseFromServer;
                    }
                    else
                    {
                        return responseFromServer;
                    }
                }



            }
            catch (Exception ex)
            {
                return ex.ToString();
            }
            return result;
        }
    }
}

Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using WebPaymentFineros.Models;
namespace WebPaymentFineros.Controllers
{
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
    public class PaymentController : ApiController
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
    {

        // GET api/values
        /// <summary>
        /// Get All Payments of Customers 
        /// </summary>
        /// <returns></returns>
        /// 
        [HttpGet]
        public IEnumerable<Payment> Get()
        {
            using (ManagerDB db = new ManagerDB())
            {
                return db.Payment.OrderByDescending(x=> x.PaymentDate).ToList();
            }
        }
        // GET api/values
        /// <summary>
        /// Get  Payment By PaymentId 
        /// </summary>
        /// <returns></returns>
      
        [HttpGet]
        public Payment Get(int id)
        {
            using (ManagerDB db = new ManagerDB())
            {
                return db.Payment.Where(x => x.PaymentId == id).FirstOrDefault();
            }
        }

        // GET api/values
        /// <summary>
        /// Get All Payments of CC Number 
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Route("GetPaymentsByCCNumber")]
        public IEnumerable<Payment> GetPaymentsByCCNumber(string val)
        {
            using (ManagerDB db = new ManagerDB())
            {

                return db.Payment.Where(x => x.CCNumber == val).ToList();

            }
        }

        // GET api/values
        /// <summary>
        /// Get All Payments of CustomerId 
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Route("GetPaymentsByCustomerId")]
        public IEnumerable<Payment> GetPaymentsByCustomerId(int customerId)
        {
            using (ManagerDB db = new ManagerDB())
            {

                return db.Payment.Where(x => x.CustomerId == customerId).ToList();

            }
        }

        // POST api/values
        /// <summary>
        /// Create New Payment 
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public String Create(Payment payment)
        {
            using (ManagerDB db = new ManagerDB())
            {
                if (payment == null)
                {
                    return "Please read Example Value";
                }
                try
                {
                    string result = "";
                    List<Customer> customer = new List<Customer>();
                    customer = db.Customer.Where(x => x.CustomerId == payment.CustomerId).ToList();
                    bool isCustomer = General.getBoolFromInt(customer.Count);
                    if (!General.NotGreatherThan(payment.Price,0))
                    {
                        result += "Price must be greather then 0  || ";
                    }
                    if (!General.NotGreatherThan(payment.CustomerId, 0))
                    {
                        result += "CustomerId must be greather then 0 || ";
                    }
                   
                    if (payment.CVV.Length != 3)
                    {
                        result += "CVV length must be 3 || ";
                    }
                    if (!isCustomer && payment.CustomerId > 0)
                    {
                        result += "CustomerId: " + payment.CustomerId + " not Found || ";
                    }
                    if (result.Length == 0)
                    {
                        db.Payment.Add(payment);
                        db.SaveChanges();
                        return "success";
                    }
                  
                    result = result.TrimEnd(' ');
                    result = result.TrimEnd('|');
                    result = result.TrimEnd('|');
                    return result;
                }
                catch (Exception ex)
                {
                   
                    return ex.ToString();
                    throw;
                }
            }
        }
    }
}

Controllers/RegisterController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using WebPaymentFineros.Models;
namespace WebPaymentFineros.Controllers
{
    public class RegisterController : Controller
    {
        // GET: Register
        public ActionResult Index()
        {
            return View();
        }
        // POST: Register/Create
        [HttpPost]
        public string Create(FormCollection formCollection)
        {
            string result = "";
            try
            {
            //TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    ManagerDB db = new ManagerDB();
                    Customer customer = new Customer();
                    customer.FirstName = formCollection["txtName"];
                    customer.LastName = formCollection["txtSurname"];
                    customer.Pw = formCollection["txtPassword"];
                    customer.Email = formCollection["txtEmail"];
                    customer.Phone = formCollection["txtPhone"];
                    customer.Age = Convert.ToInt32(formCollection["txtAge"]);
                    string strParams = JsonConvert.SerializeObject(customer);
                    string urlCreate =General.GetDomain() + "api/Customer";
                    string responseFromServer = General.SendJSonData(urlCreate, strParams).Replace("\"", "");
                    if (responseFromServer == "success")
                    {
                         //RedirectToAction("Login", "Home");
                        return responseFromServer;
                    }
                    else
                    {
                        return responseFromServer;
                    }
                }
             


            }
            catch(Exception ex)
            {
                return ex.ToString();
            }
            return result;
        }

       
    }
}

Views/Home/Customer.cshtml
@model IEnumerable<WebPaymentFineros.Models.Customer>
@{
    ViewBag.Title = "Customer List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Customer List</h2>
<table class="table">
    <thead>
        <tr>
            @*<th>
                @Html.DisplayNameFor(model => model.CustomerId)
            </th>*@

            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>


            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>



            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                @*<td>
                    @Html.DisplayFor(modelItem => item.CustomerId)
                </td>*@

                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Age)
                </td>





                @*<td>
            <a style="cursor:pointer;" asp-action="Edit" asp-route-id="@item.SubjectID">İncele</a>
        </td>*@
            </tr>

        }
</table>

Views/Home/Index.cshtml
@model IEnumerable<WebPaymentFineros.Models.MyProduct>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Products</h2>

<div class="container" style="margin-top:120px; margin-bottom:120px;">

    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">@item.ProductName</h5>
                        <p class="card-text">@item.Price $</p>
                        @*<a href="#" class="btn btn-primary">Buy product</a>*@
                        @Html.ActionLink("Buy Product", "PaymentCheckOut", "Home", routeValues: new { @id = item.ProductId }, htmlAttributes: new { })
                    </div>
                </div>
            </div>

        }


    </div>
</div>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalLong">
    Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

Views/Home/Login.cshtml
@{
    ViewBag.Title = "Customer Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Customer Login</h2>
<form id="loginForm" method="post">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <input id="txtEmail" class="form-control" type="email" style="max-width: 100%; width: 100%;" name="txtEmail" value="" placeholder="Email" />

            </div>

            <div class="col-lg-3">
                <input id="txtPassword" class="form-control" type="password" style="max-width: 100%; width: 100%;" name="txtPassword" value="" placeholder="Password" />

            </div>


        </div>


        <div class="row" style="margin-top:30px; width:100%;">
            <div class="col-lg-6" style="width:50%; float:left;">
                <input id="btnLogin" type="submit" class="btn btn-danger" style="max-width:100%; width:100%; height:40px;" name="paylas" value="Login" placeholder="Message" />

            </div>
          
        </div>
     

    </div>
  

    <script type="text/javascript">
       
        document.getElementById('btnLogin').onclick = evt => {
            evt.preventDefault();
            /*  console.log($('#txtEmail')[0].value);*/
            var required = '';
            var validation = '';
            var result = '';
            if ($('#txtEmail')[0].value == '') {
                alert('Email is required');
                required += 'Email is required;';
            }
            if ($('#txtPassword')[0].value == '') {
                required += 'Password is required;';
            }
            var expr = /^([\w-\.]+)@@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/;
            if ($('#txtEmail')[0].value.length>0) {
                if (!expr.test($('#txtEmail')[0].value)) {
                    validation += 'You have entered an invalid email address;';
                }
            }
          
            result = required.toString() + validation.toString();
            if (result.length > 0) {
                alert(result);
                return;
            }

            $.ajax({
                url: "/Login/CheckUser",
                data: $('#loginForm').serialize(),
                type: 'POST',

                success: function (data) {
                    if (data == 'success') {
                        window.location.href = "/Home/Index";
                    }
                    else {
                        alert(data);
                    }

                },
                error: function (err) {
                    alert(err);
                }

            });
        }

  

    </script>
</form>

Views/Home/Payment.cshtml
@model IEnumerable<WebPaymentFineros.Models.Payment>

@{
    ViewBag.Title = "Payment";
    Layout = "~/Views/Shared/_Layout.cshtml";
    WebPaymentFineros.Models.ManagerDB d = new WebPaymentFineros.Models.ManagerDB();

    List<WebPaymentFineros.Models.Customer> customers = new List<WebPaymentFineros.Models.Customer>();
    customers = d.GetCustomer();

}

<h2>Payment</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Surname
            </th>

            <th>
                @Html.DisplayNameFor(model => model.CCNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CCDate)
            </th>


            <th>
                @Html.DisplayNameFor(model => model.CVV)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PaymentDate)
            </th>


            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => (customers.Where(x => x.CustomerId == item.CustomerId).FirstOrDefault().FirstName))
                </td>
                <td>
                    @Html.DisplayFor(modelItem => (customers.Where(x => x.CustomerId == item.CustomerId).FirstOrDefault().LastName))
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CCNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CCDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CVV)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price) $
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PaymentDate) 
                </td>



                @*<td>
            <a style="cursor:pointer;" asp-action="Edit" asp-route-id="@item.SubjectID">İncele</a>
        </td>*@
            </tr>

        }
</table>

Views/Home/PaymentCheckOut.cshtml
@{
    ViewBag.Title = "Payment CheckOut";
    Layout = "~/Views/Shared/_Layout.cshtml";
    WebPaymentFineros.Models.ManagerDB d = new WebPaymentFineros.Models.ManagerDB();

    WebPaymentFineros.Models.MyProduct singleProduct = new WebPaymentFineros.Models.MyProduct();
    var productId = ViewContext.RouteData.Values["id"];
    singleProduct = d.GetProductById(Convert.ToInt32(productId));
}

<h2>Payment CheckOut</h2>
<form id="paymentForm" method="post">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">

                @singleProduct.ProductName
            </div>
            <div class="col-lg-6">
                @singleProduct.Price $
                <input type="hidden" id="productId" name="hidProductId" value="@singleProduct.ProductId">
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <input id="txtCCNameSurname" class="form-control" type="email" style="max-width: 100%; width: 100%;" name="txtCCNameSurname" maxlength="100" value="" placeholder="CC Name Surname" />

            </div>
            <div class="col-lg-6">
                <input id="txtCCNumber" class="form-control" type="text" style="max-width: 100%; width: 100%;" name="txtCCNumber" maxlength="16" value="" placeholder="CC Number" />

            </div>
        </div>
        <div class="row">
            <div class="col-lg-4">
                <div class="form-group">
                    <select class="form-control" name="selM" id="selM">
                        <option>Select monthh</option>
                        <option>01</option>
                        <option>02</option>
                        <option>03</option>
                        <option>04</option>
                        <option>05</option>
                        <option>06</option>
                        <option>07</option>
                        <option>08</option>
                        <option>09</option>
                        <option>10</option>
                        <option>11</option>
                        <option>12</option>
                    </select>
                </div>


            </div>
            <div class="col-lg-4">
                <div class="form-group">
                    <select class="form-control" name="selY" id="selY">
                        <option>Select year</option>
                        <option>2022</option>
                        <option>2023</option>
                        <option>2024</option>
                        <option>2025</option>
                        <option>2026</option>
                        <option>2027</option>
                        <option>2028</option>
                        <option>2029</option>
                        <option>2030</option>
                        <option>2031</option>
                        <option>2032</option>
                        <option>2033</option>
                        <option>2034</option>
                    </select>
                </div>


            </div>


            <div class="col-lg-4">
                <input id="txtCVV" class="form-control" type="text" style="max-width: 100%; width: 100%;" name="txtCVV" maxlength="3" value="" placeholder="CVV" />

            </div>

        </div>



        <div class="row" style="margin-top:30px; width:100%;">
            <div class="col-lg-6" style="width:50%; float:left;">
                <input id="btnPayment" type="submit" class="btn btn-danger" style="max-width:100%; width:100%; height:40px;" name="paylas" value="Buy" />

            </div>

        </div>


    </div>
  

    <script type="text/javascript">
       
        document.getElementById('btnPayment').onclick = evt => {
            evt.preventDefault();
            /*  console.log($('#txtEmail')[0].value);*/
            var required = '';
            var validation = '';
            var result = '';
            if ($('#txtCCNameSurname')[0].value == '') {
                required += 'CC Name Surname is required;';
            }
            if ($('#txtCCNumber')[0].value == '') {
                required += 'CC Number is required;';
            }
            if ($('#selM')[0].selectedIndex == 0) {
                required += 'CC month required;';
            }
            if ($('#selY')[0].selectedIndex == 0) {
                required += 'CC year required;';
            }
            if ($('#txtCVV')[0].value == '') {
                required += 'CVV is required;';
            }
            var regexNumber = /^[0-9]{16}$/;
            var regexCVV = /^[0-9]{3}$/;
          
            if ($('#txtCVV')[0].value.length>0) {
                if (!regexCVV.test($('#txtCVV')[0].value)) {
                    validation += 'You have entered an invalid CVV Number;';
                }
            }
            if ($('#txtCCNumber')[0].value.length > 0) {
                if (!regexNumber.test($('#txtCCNumber')[0].value)) {
                    validation += 'You have entered an invalid CC Number;';
                }
            }
           
            result = required.toString() + validation.toString();
            if (result.length > 0) {
                alert(result);
                return;
            }

            $.ajax({
                url: "/PaymentCheckOut/Create",
                data: $('#paymentForm').serialize(),
                type: 'POST',

                success: function (data) {
                    if (data == 'success') {
                        window.location.href = "/Home/Payment";
                    }
                    else {
                        alert(data);
                    }

                },
                error: function (err) {
                    alert(err);
                }

            });
        }

  

    </script>
</form>